name: Build

on:
  pull_request:

# If another web build starts for the same branch, cancel the previous build. This
# protects us from two builds trying to upload at the same time and clobbering each
# other.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_website:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      LOGURU_LEVEL: DEBUG
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org/ | python -
      - name: Add Poetry to PATH
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install
      - name: Run Black
        run: poetry run black --check src/ tests/
      - name: Run Isort
        run: poetry run isort --check src/ tests/
      - name: Run Pytest
        run: poetry run pytest
      - name: Download ATT&CK data
        run: poetry run download_attack_stix --stix20 --all -d data/attack
      - name: Build website
        env:
          LOGURU_LEVEL: INFO
        run: poetry run build-attack-sync --url-prefix 'https://mappingsexplorer.z13.web.core.windows.net/${{env.BRANCH_NAME}}/'
      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: attack_sync_html_preview
          path: public/
  azure_blob:
    if: github.ref_name != 'main'
    needs: build_preview
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: mappingsexplorer
      AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      STATICRYPT_PASS: ${{ secrets.STATICRYPT_PASS }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g staticrypt
      - name: Download Web Site
        uses: actions/download-artifact@v4
        with:
          name: attack_sync_html_preview
          path: .
      - name: Decompress Artifacts
        run: unzip -q output.zip
      - env:
          STATICRYPT_PASS: ${{ secrets.STATICRYPT_PASS }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: >
          staticrypt --remember 30 --salt c0c22fdf0cd9d2a099db9c90ca4a58bf \
            --password $STATICRYPT_PASS --short \
            --template-title "Mappings Explorer (branch: '${{ env.BRANCH_NAME }}/*'" \
            --template-instructions "The contents of this site are marked TLP:AMBER:CTID-R&D:22-80. Do not share with unauthorized individuals." \
            --template-color-primary "#6241c5" \
            --template-color-secondary "#b2b2b2" \
            --template-button "Log In" \
            -r output/
      - name: Ensure StatiCrypt ran # StatiCrypt will fail without warning; verify it created a directory
        run: test -d encrypted
      - name: Copy encrypted HTML files
        run: rsync -Ir -v --include='*.html' --exclude='*.*' encrypted/output .
      - name: Set the branch name
        run: mv output ${{ env.BRANCH_NAME }}
      - name: Install Azure CLI
        run: pip install azure-cli==2.76.0
      - name: Delete old blobs
        run: az storage blob delete-batch -s '$web' --pattern '${{ env.BRANCH_NAME }}/*'
      - name: Upload to blob storage
        run: az storage blob upload-batch -s . --pattern '${{ env.BRANCH_NAME }}/*' -d '$web'
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This PR has been published to https://mappingsexplorer.z13.web.core.windows.net/${process.env['BRANCH_NAME']}/`,
            })
